[tool.poetry]
name = "tyme"
version = "0.1.5"
description = "track your moments everywhere"
authors = ["Enrico Borba <enricozb@gmail.com>"]

[tool.poetry.scripts]
tyme = "tyme.cli.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
hjson = "^3.0"
colorama = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
