language: python
python: 2.7
#virtualenv:
#    system_site_packages: false

# run in virtualization environment with high memory (7.5 GB)
# https://docs.travis-ci.com/user/reference/overview/#virtualization-environments
# sudo: required
# dist: trusty

env:
#    - CONDA_PYTHON_VERSION=2.7
    - CONDA_PYTHON_VERSION=3.6
    - CONDA_PYTHON_VERSION=3.7

before_install:
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$CONDA_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
#    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#    - chmod +x miniconda.sh
#    - ./miniconda.sh -b
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

# command to install dependencies
install:
    - conda config --add channels conda-forge
    - conda config --add channels SimpleITK
    - conda config --add channels mjirik
    - conda update --yes conda
    - conda create --yes -n travis pip python=$CONDA_PYTHON_VERSION pytest-cov
    - source activate travis
    - conda install --yes --file requirements_conda.txt python=$CONDA_PYTHON_VERSION
    - pip install -r requirements_pip.txt
    - python -m io3d.datasets -l 3Dircadb1.1

# command to run tests
# using "travis_wait MIN" to stop travis from terminating after 10min of no output.
# Note: travis_wait time is shared between different python versions!
script: # travis_wait 180 nosetests -v -s --with-coverage --cover-package=bodynavigation
    - travis_wait 180 python -m pytest --cov=bodynavigation/
after_success:
    - coveralls
