[tool.poetry]
name = "DogAge"
version = "0.0.3"
description = "Programms for DogAge Challenge"
authors = ["Aleksandr Sinitca <siniza.s.94@gmail.com>"]
packages = [
    {include = "DogAge"},
]
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.poetry.scripts]
dogage_validate = 'DogAge:dogage_validate.main'

[tool.poetry.dependencies]
python = "^3.6"
pandas = ""
argparse = ""
sklearn = ""
matplotlib = ""
numpy = ""


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
